// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8aFKimFaB2rab9oQiPGrmMv4KD4nsVk',
    appId: '1:87208773389:web:37fbfdb6d927a77af45244',
    messagingSenderId: '87208773389',
    projectId: 'test-ios-63f0a',
    authDomain: 'test-ios-63f0a.firebaseapp.com',
    storageBucket: 'test-ios-63f0a.appspot.com',
    measurementId: 'G-91YSYMG5Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ci3xSc4Fbx_m78bbtESZR1dbz3KozN0',
    appId: '1:87208773389:android:f9565e084760e549f45244',
    messagingSenderId: '87208773389',
    projectId: 'test-ios-63f0a',
    storageBucket: 'test-ios-63f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYD2jnSNwEe5cXaUxrGWPuhTs-W-wGK6s',
    appId: '1:87208773389:ios:9bae844e30ebe448f45244',
    messagingSenderId: '87208773389',
    projectId: 'test-ios-63f0a',
    storageBucket: 'test-ios-63f0a.appspot.com',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYD2jnSNwEe5cXaUxrGWPuhTs-W-wGK6s',
    appId: '1:87208773389:ios:0b0d8c36d0dc349df45244',
    messagingSenderId: '87208773389',
    projectId: 'test-ios-63f0a',
    storageBucket: 'test-ios-63f0a.appspot.com',
    iosBundleId: 'com.example.projectFirebase.RunnerTests',
  );
}
